FROM node:18-bullseye

WORKDIR /srv/asr-frontend

COPY app/frontend/package*.json ./app/frontend/
RUN cd app/frontend && npm install

COPY app/frontend ./app/frontend

WORKDIR /srv/asr-frontend/app/frontend

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
