version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      ASR_SAFE_MODE: "true"
    volumes:
      - ./data:/srv/asr/data
      - ./out:/srv/asr/out
      - ./logs:/srv/asr/logs
    depends_on: []

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE: "http://localhost:8000/api"
    depends_on:
      - backend
