[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
select = ["E", "F", "B", "I", "UP", "S"]
ignore = ["E203", "E266", "E501", "S101"]
fix = true
exclude = ["app/frontend"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra --strict-markers"
testpaths = ["app/tests"]
markers = [
    "live: integration tests that hit live services (requires credentials)",
]

[tool.coverage.run]
branch = true
source = ["app"]
