repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
        additional_dependencies: ["click<8.1.4"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: ["--py310-plus"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.0.3
          - prettier-plugin-tailwindcss@0.5.4
        files: "\\.(ts|tsx|js|jsx|json|css|md)$"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.50.0
    hooks:
      - id: eslint
        files: "\\.(ts|tsx)$"
        additional_dependencies:
          - eslint@8.50.0
          - eslint-config-prettier@9.0.0
          - eslint-plugin-react@7.33.2
          - eslint-plugin-react-hooks@4.6.0
          - @typescript-eslint/eslint-plugin@6.7.2
          - @typescript-eslint/parser@6.7.2
