name: Refresh Media Assets

on:
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright imageio markdown
          python -m playwright install --with-deps chromium

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: app/frontend/package-lock.json

      - name: Install frontend dependencies & build
        working-directory: app/frontend
        run: |
          npm install
          npm run build

      - name: Generate screenshots
        env:
          PYTHONPATH: .
        run: |
          python app/scripts/capture_media.py

      - name: Upload media artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-media
          path: |
            docs/media/dashboard.png
            docs/media/status-pack.png
            docs/media/demo-flow.gif
          retention-days: 7
