name: Scorecard

on:
  schedule:
    - cron: '0 3 * * 1'
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@v2.4.3
        with:
          results_file: results.sarif
          publish_results: true

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: scorecard-results
          path: results.sarif
